<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="1To4_tests.OneToFour_Tests-20151201161551" tests="4" time="0.479">
	<testcase classname="1To4_tests.OneToFour_Tests" name="test_02" time="0.114"/>
	<testcase classname="1To4_tests.OneToFour_Tests" name="test_03" time="0.111"/>
	<testcase classname="1To4_tests.OneToFour_Tests" name="test_04" time="0.122"/>
	<testcase classname="1To4_tests.OneToFour_Tests" name="test_01" time="0.132">
		<error message="getJsonObjectFromResults() missing 1 required positional argument: 'self'" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/home/gaems-dev/Escritorio/EGC/agora-results-tests/src/unittest/python/1To4_tests.py", line 19, in test_01
    jsonObject = utils.getJsonObjectFromResults()
TypeError: getJsonObjectFromResults() missing 1 required positional argument: 'self'
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
