<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="4" failures="0" name="test1To4_tests.Test1To4-20151201162852" tests="4" time="0.390">
	<testcase classname="test1To4_tests.Test1To4" name="test_01" time="0.083">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "/home/gaems-dev/Escritorio/EGC/agora-results-tests/src/unittest/python/test1To4_tests.py", line 25, in test_01
    jsonObject = json.loads(data)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="test1To4_tests.Test1To4" name="test_02" time="0.101">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "/home/gaems-dev/Escritorio/EGC/agora-results-tests/src/unittest/python/test1To4_tests.py", line 42, in test_02
    jsonObject = json.loads(data)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="test1To4_tests.Test1To4" name="test_03" time="0.097">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "/home/gaems-dev/Escritorio/EGC/agora-results-tests/src/unittest/python/test1To4_tests.py", line 59, in test_03
    jsonObject = json.loads(data)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<testcase classname="test1To4_tests.Test1To4" name="test_04" time="0.109">
		<error message="Expecting value: line 1 column 1 (char 0)" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "/home/gaems-dev/Escritorio/EGC/agora-results-tests/src/unittest/python/test1To4_tests.py", line 76, in test_04
    jsonObject = json.loads(data)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
