<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="3" name="5To8_tests.tests-20151201172407" tests="4" time="0.474">
	<testcase classname="5To8_tests.tests" name="test_05" time="0.130"/>
	<testcase classname="5To8_tests.tests" name="test_06" time="0.117">
		<failure message="0 != None" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/gaems-dev/Escritorio/EGC/agora-results-tests/src/unittest/python/5To8_tests.py", line 37, in test_06
    self.assertEqual(jsonObjectAnswers[0]["winner_position"], None)
AssertionError: 0 != None
]]>		</failure>
	</testcase>
	<testcase classname="5To8_tests.tests" name="test_07" time="0.114">
		<failure message="0 != None" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/gaems-dev/Escritorio/EGC/agora-results-tests/src/unittest/python/5To8_tests.py", line 57, in test_07
    self.assertEqual(jsonObjectAnswers[0]["winner_position"], None)
AssertionError: 0 != None
]]>		</failure>
	</testcase>
	<testcase classname="5To8_tests.tests" name="test_no_winner_with_null_votes" time="0.113">
		<failure message="0 != None" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/gaems-dev/Escritorio/EGC/agora-results-tests/src/unittest/python/5To8_tests.py", line 77, in test_no_winner_with_null_votes
    self.assertEqual(jsonObjectAnswers[0]["winner_position"], None)
AssertionError: 0 != None
]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
