<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="1To4_tests.OneToFour_Tests-20151201161523" tests="4" time="0.375">
	<testcase classname="1To4_tests.OneToFour_Tests" name="test_02" time="0.136"/>
	<testcase classname="1To4_tests.OneToFour_Tests" name="test_03" time="0.119"/>
	<testcase classname="1To4_tests.OneToFour_Tests" name="test_04" time="0.119"/>
	<testcase classname="1To4_tests.OneToFour_Tests" name="test_01" time="0.001">
		<error message="name 'os' is not defined" type="NameError">
<![CDATA[Traceback (most recent call last):
  File "/home/gaems-dev/Escritorio/EGC/agora-results-tests/src/unittest/python/1To4_tests.py", line 17, in test_01
    utils.executeAgoraResults('test_01')
  File "/home/gaems-dev/Escritorio/EGC/agora-results-tests/src/main/python/utils.py", line 5, in executeAgoraResults
    os.system('agora-results -t res/'+tally+'.tar.gz -s > results')
NameError: name 'os' is not defined
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
